[build]
  command = "npm run build"
   functions="Ftions"
  publish = ".next"
 
[functions]
  directory = "Ftions"
  node_bundler = "esbuild"
  [functions.post]
    included_files = ["post/*.md"]
  
  [[redirects]]
  from = "/post/*"
  to = "/.netlify/Ftions/post-1001.js"
  status = 200
  force = false
  querty = { lang = ":lang" }


  


[dev]
  autoLaunch = false
  
[[plugins]]
  package = "netlify-plugin-cypress"
  

